### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by bikhilall** [wannesvl/matlabneos#1]
I added he java path and runned  neos = NeosInterface() and face the following error:

Error using NeosInterface (line 18)
Java exception occurred:
redstone.xmlrpc.XmlRpcException: A network error occurred.

	at redstone.xmlrpc.XmlRpcClient.endCall(Unknown Source)

	at redstone.xmlrpc.XmlRpcClient.invoke(Unknown Source)

Caused by: java.net.ConnectException: Connection timed out: connect

	at java.net.DualStackPlainSocketImpl.connect0(Native Method)

	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)

	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)

	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)

	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)

	at java.net.PlainSocketImpl.connect(Unknown Source)

	at java.net.SocksSocketImpl.connect(Unknown Source)

	at java.net.Socket.connect(Unknown Source)

	at java.net.Socket.connect(Unknown Source)

	at sun.net.NetworkClient.doConnect(Unknown Source)

	at sun.net.www.http.HttpClient.openServer(Unknown Source)

	at sun.net.www.http.HttpClient.openServer(Unknown Source)

	at sun.net.www.http.HttpClient.<init>(Unknown Source)

	at sun.net.www.http.HttpClient.New(Unknown Source)

	at sun.net.www.http.HttpClient.New(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)

	... 2 more

**Comment by bikhilall** [comment]
Suggested fix:

change port and address in the NeosInterface function to

old URL: http://neos-server.org:3332
new URL: https://neos-server.org:3333

**Comment by wannesvanloock** [comment]
Thanks for fixing! I had no idea people were actually using this.
Please make a pull request with the proposed fix.
